### PR TITLE
(maint) updated build pipeline

### PR DESCRIPTION
**Pull request by nils-a**
* Updated .NET to 3.1 in build
* Updated unit tests to target .NET 3.1
* switched from .NET Framework runner for Cake to .NET tool runner
* updated Cake to 0.38.5 in build (the last version before 1.0.0)
* Bumped build Azure Pipeline images to versions that work with Cake 0.38.5
* Bumped the reference of Cake.JSON to 5.0.0 because of Newtonsoft.JSON errors
* switched from deprecated TFBuild* commands to newer AzurePipeline commands

### CODE REVIEW

**Comment by nils-a** [comment]
@binick I saw that you tried to update the build pipeline in https://github.com/cake-contrib/Cake.Board/pull/49. Maybe this PR helps a bit. 😄

**Comment by binick** [comment]
Hi @nils-a,
thank you so much for you contribution.

I rolled back `build.ps1` to maintain its features.

Thanks again for the rest 🙂.

**Comment by nils-a** [comment]
@binick glad I could help. Is there a reason you prefer the .NET framework runner?
It has been deprecated in favor of the .NET tool runner, see [Sunsetting of .NET Framework and .NET Core runners in Cake 2.0](https://cakebuild.net/blog/2021/10/sunsetting-runners)

If you feel there are features missing in the .NET tool runner, I'd like to hear them. 😀

**Comment by binick** [comment]
Unfortunately, for work reasons I had to move away from Cake and this project ended up in the corner :(

In the early days, dotnet versions were changing every couple of days. So having the download of the correct version of the SDK was a killer feature for me.

With the arrival of .NET 6 it will probably be a good time to switch to Cake .NET Tool and who knows, maybe dust off this project.

**Comment by nils-a** [comment]
> Unfortunately, for work reasons I had to move away from Cake and this project ended up in the corner :(

Now, that's kind of sad. Thanks for keeping this project alive 👍 
If you need any help, I'd be willing to put in a PR or two 😄 

Have you seen that there are now two "helpers" for addins: [CakeContrib.Guidelines](https://github.com/cake-contrib/CakeContrib.Guidelines) which will help with a couple of best practices / guidelines and [Cake.Addin.Analyzer](https://github.com/WormieCorp/Cake.Addin.Analyzer) which provides a roslyn analyser for cake addins.

**Pull request merged**
